spring:
  application:
    name: uno-server

  # Configuración de Base de Datos PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/uno_game_db
    username: uno_user
    password: uno_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Configuración JPA/Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # Usamos 'validate' porque Flyway maneja las migraciones
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  # Configuración de Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true

  # Configuración de WebSocket
  websocket:
    max-text-message-size: 65536
    max-binary-message-size: 65536

# Configuración del Servidor
server:
  port: 8080
  servlet:
    context-path: /api

# Configuración de Logging
logging:
  level:
    dev.rodrigovaamonde.unoserver: INFO
    org.springframework.web.socket: DEBUG
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configuración de documentación OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
